name: Build and Push Docker Image

on:
    push:
        branches: [ "main" ] # Déclenche le build lors d'un push sur main

env:
    REGISTRY: ghcr.io
    REPOSITORY_NAME: Nicolas-Choquet-pour-MediaSchool-Nice/realisation-professionnelle-bts-2-slam-iris

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup .env
              run: |
                  echo "APP_ENV=dev" >> .env
                  echo "APP_SECRET=$(openssl rand -hex 30)" >> .env
                  echo "APP_SHARE_DIR=var/share" >> .env
                  echo "DEFAULT_URI=http://localhost" >> .env
                  echo "DATABASE_URL=postgresql://nchoquet:nchoquet@127.0.0.1:5432/roombooking?serverVersion=16&charset=utf8" >> .env
                  echo "MAILER_DSN=null://null" >> .env
                  echo "MESSENGER_TRANSPORT_DSN=doctrine://default?auto_setup=0" >> .env

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
               php-version: '8.4'
               extensions: intl, pdo_pgsql, zip, opcache # Les mêmes que ton Dockerfile
               coverage: none

                      # 2. LANCER COMPOSER UPDATE (ou install)
            - name: Update Composer dependencies
              run: composer update --no-interaction --prefer-dist --optimize-autoloader

            - name: Prepare Image Name
              run: |
                # On convertit "Organisation/NomDuRepo" en "organisation/nomdurepo"
                # C'est ce format exact qui est requis par ghcr.io
                REPO_LOWER=$(echo "${{ env.REPOSITORY_NAME }}" | tr '[:upper:]' '[:lower:]')
                echo "IMAGE_NAME=$REPO_LOWER" >> $GITHUB_ENV

            - name: Log in to the Container registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GH_PACKAGES_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: |
                      ghcr.io/${{ env.REPOSITORY_NAME }}:latest
                      ghcr.io/${{ env.REPOSITORY_NAME }}:${{ github.sha }}
