name: Build and Deploy Docker Image

on:
    push:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup .env
              run: |
                  echo "APP_ENV=dev" >> .env
                  echo "APP_SECRET=$(openssl rand -hex 30)" >> .env
                  echo "APP_SHARE_DIR=var/share" >> .env
                  echo "DEFAULT_URI=http://localhost" >> .env
                  echo "DATABASE_URL=postgresql://nchoquet:nchoquet@127.0.0.1:5432/roombooking?serverVersion=16&charset=utf8" >> .env
                  echo "MAILER_DSN=null://null" >> .env
                  echo "MESSENGER_TRANSPORT_DSN=doctrine://default?auto_setup=0" >> .env

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
               php-version: '8.4'
               extensions: intl, pdo_pgsql, zip, opcache # Les mêmes que ton Dockerfile
               coverage: none

                      # 2. LANCER COMPOSER UPDATE (ou install)
            - name: Update Composer dependencies
              run: composer update --no-interaction --prefer-dist --optimize-autoloader

            - name: Log in to the Container registry
              run: echo "${{ secrets.GH_PACKAGES_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
              #uses: docker/login-action@v3
              #with:
              #    registry: ghcr.io
              #    username: ${{ github.actor }}
              #    password: ${{ secrets.GH_PACKAGES_TOKEN }}

            - name: Build and push
              run: |
                  # On définit les variables en local dans le shell pour éviter les surprises
                  REPO_OWNER=${{ github.repository_owner }}
                  REPO_NAME=${{ github.event.repository.name }}
                  IMAGE_ID=ghcr.io/$REPO_OWNER/$REPO_NAME

                  echo "Build de l'image : $IMAGE_ID"

                  docker build . -t $IMAGE_ID:latest
                  docker push $IMAGE_ID:latest
